Update utils.lua
ringwormGO-organization/Termi-Lua pull request #6
Opened 2023-12-17 14:36 UTC by EndermanPC

2023-12-17 14:45 UTC, Andrej123456789 commented
This pull request is one of the best we received ever! Thanks a lot

2023-12-17 20:16 UTC, Andrej123456789 requested changes

2023-12-17 20:16 UTC, Andrej123456789 commented on src/functions/utils/utils.lua
> +    str:gsub(".", function(c) table.insert(t, c) end)
Replace this line with `table.insert(t, str)` so Lua don't print each letter in new line!

2023-12-19 11:03 UTC, StjepanBM1 commented
I will merge this

2023-12-19 11:03 UTC, merged